server:
  port: 8080

spring:
  application:
    name: ead-api-gateway # Nome da aplicação para o Eureka
  cloud:
    gateway:
      routes: # Rotas para os serviços que o gateway vai redirecionar
        - id: authuser-service # Id de identificação da rota
          uri: lb://ead-authuser-service # Nome da URI que o serviço se registrou no registry, o lb faz o balanceamento de carga
          predicates:
            - Path=/ead-authuser/** # Tudo que vier apos 'ead-authuser' será redirecionado para a uri 'ead-authuser-service', tem que ser inserido no context-path do respectivo serviço
        - id: course-service
          uri: lb://ead-course-service
          predicates:
            - Path=/ead-course/**

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka' # Endereço onde está disponível o registry, para o api gateway se registrar nele
  instance:
    hostname: localhost
